# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
version: "3"
services:
  ckan:
    container_name: ckan
    # image: ckan/ckan:latest
    ## or build CKAN master:
    build: ../../
    links:
      - db
      - solr
      - redis
    ports:
      - "80:5000"
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - SOLR_PORT_8983_TCP_ADDR=solr
      - SOLR_PORT_8983_TCP_PORT=8983
      - REDIS_PORT_6379_TCP_ADDR=redis

  db:
    container_name: db
    build:
      context: postgresql/
      #args:
      #  - POSTGRES_USER=${POSTGRES_USER}
      #  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #  - POSTGRES_DB=${POSTGRES_DB}
    #environment:
      #- POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
  solr:
    container_name: solr
    image: ckan/solr:latest

  redis:
    container_name: redis
    image: redis:latest
